// Generated by scripts/import-nova-docs.mjs. Do not edit manually.

export const novaSidebar = [
  {
    "text": "NovaCore",
    "collapsed": false,
    "items": [
      {
        "text": "Начало",
        "collapsed": false,
        "items": [
          {
            "text": "Что такое Nova",
            "link": "/nova/core/intro"
          },
          {
            "text": "Первый NovaApp",
            "link": "/nova/core/first-app"
          },
          {
            "text": "TypeScript и DSL",
            "link": "/nova/core/ts-dsl"
          }
        ]
      },
      {
        "text": "Основные понятия",
        "collapsed": true,
        "items": [
          {
            "text": "NovaApp",
            "link": "/nova/core/nova-app"
          },
          {
            "text": "Сцена",
            "link": "/nova/core/scene"
          },
          {
            "text": "Surface и слои",
            "link": "/nova/core/surfaces"
          },
          {
            "text": "Node и дерево сцены",
            "link": "/nova/core/nodes"
          },
          {
            "text": "Жизненный цикл объектов",
            "link": "/nova/core/lifecycle"
          }
        ]
      },
      {
        "text": "Отрисовка",
        "collapsed": true,
        "items": [
          {
            "text": "Schema primitives",
            "link": "/nova/core/schema-primitives"
          },
          {
            "text": "Text, icons и texture",
            "link": "/nova/core/text-icons-texture"
          },
          {
            "text": "Assets v2",
            "link": "/nova/core/assets-v2"
          },
          {
            "text": "Bounds, transform и zIndex",
            "link": "/nova/core/bounds-transform-zindex"
          },
          {
            "text": "Raw schema",
            "link": "/nova/core/raw-schema"
          },
          {
            "text": "Custom nodes",
            "link": "/nova/core/custom-nodes"
          },
          {
            "text": "Порядок отрисовки",
            "link": "/nova/core/render-order"
          }
        ]
      },
      {
        "text": "Взаимодействие",
        "collapsed": true,
        "items": [
          {
            "text": "Pointer events",
            "link": "/nova/core/pointer-events"
          },
          {
            "text": "Drag lifecycle",
            "link": "/nova/core/drag-lifecycle"
          },
          {
            "text": "Pointer capture",
            "link": "/nova/core/pointer-capture"
          },
          {
            "text": "Hit-test",
            "link": "/nova/core/hit-test"
          },
          {
            "text": "Focus и keyboard",
            "link": "/nova/core/focus-keyboard"
          },
          {
            "text": "Selection",
            "link": "/nova/core/selection"
          },
          {
            "text": "Cursor state",
            "link": "/nova/core/cursor-state"
          }
        ]
      },
      {
        "text": "DSL и стили",
        "collapsed": true,
        "items": [
          {
            "text": "Зачем нужен DSL",
            "link": "/nova/core/dsl-purpose"
          },
          {
            "text": "Файлы `.nova`",
            "link": "/nova/core/nova-files"
          },
          {
            "text": "DSL entrypoint",
            "link": "/nova/core/dsl-entrypoint"
          },
          {
            "text": "Реактивность DSL",
            "link": "/nova/core/reactivity"
          },
          {
            "text": "NovaCSS",
            "link": "/nova/core/novacss"
          },
          {
            "text": "Scoped styles",
            "link": "/nova/core/scoped-styles"
          },
          {
            "text": "Selectors",
            "link": "/nova/core/selectors"
          },
          {
            "text": "Theme tokens",
            "link": "/nova/core/theme-tokens"
          },
          {
            "text": "Validation",
            "link": "/nova/core/validation"
          },
          {
            "text": "Debug generated output",
            "link": "/nova/core/debug-output"
          }
        ]
      },
      {
        "text": "Организация приложения",
        "collapsed": true,
        "items": [
          {
            "text": "Canvas во Vue",
            "link": "/nova/core/vue-canvas"
          },
          {
            "text": "Структура сцен",
            "link": "/nova/core/scene-structure"
          },
          {
            "text": "Структура nodes",
            "link": "/nova/core/node-structure"
          },
          {
            "text": "Assets и resources",
            "link": "/nova/core/assets-resources"
          },
          {
            "text": "Cleanup и destroy",
            "link": "/nova/core/cleanup-destroy"
          },
          {
            "text": "Error handling",
            "link": "/nova/core/error-handling"
          }
        ]
      },
      {
        "text": "Справочник",
        "collapsed": true,
        "items": [
          {
            "text": "`NovaApp`",
            "link": "/nova/core/reference-nova-app"
          },
          {
            "text": "`NovaScene`",
            "link": "/nova/core/reference-nova-scene"
          },
          {
            "text": "`NovaSurface`",
            "link": "/nova/core/reference-nova-surface"
          },
          {
            "text": "`NovaNode`",
            "link": "/nova/core/reference-nova-node"
          },
          {
            "text": "Контракты schema",
            "link": "/nova/core/reference-schema"
          },
          {
            "text": "Контракты событий",
            "link": "/nova/core/reference-events"
          },
          {
            "text": "Theme API",
            "link": "/nova/core/reference-theme"
          },
          {
            "text": "Package exports",
            "link": "/nova/core/reference-exports"
          }
        ]
      }
    ]
  },
  {
    "text": "NovaUIKit",
    "collapsed": true,
    "items": [
      {
        "text": "Начало",
        "collapsed": false,
        "items": [
          {
            "text": "Что такое Nova UI Kit",
            "link": "/nova/uikit/intro"
          },
          {
            "text": "Первый компонент",
            "link": "/nova/uikit/first-component"
          },
          {
            "text": "TypeScript и DSL",
            "link": "/nova/uikit/ts-dsl"
          },
          {
            "text": "Интеграция с NovaCore",
            "link": "/nova/uikit/core-integration"
          }
        ]
      },
      {
        "text": "Основы",
        "collapsed": true,
        "items": [
          {
            "text": "Root",
            "link": "/nova/uikit/root"
          },
          {
            "text": "Layout model",
            "link": "/nova/uikit/layout-model"
          },
          {
            "text": "Style properties",
            "link": "/nova/uikit/style-properties"
          },
          {
            "text": "Theme tokens",
            "link": "/nova/uikit/theme-tokens"
          },
          {
            "text": "Events",
            "link": "/nova/uikit/events"
          },
          {
            "text": "Lifecycle",
            "link": "/nova/uikit/lifecycle"
          }
        ]
      },
      {
        "text": "Примитивы layout",
        "collapsed": true,
        "items": [
          {
            "text": "Surface",
            "link": "/nova/uikit/surface"
          },
          {
            "text": "Panel",
            "link": "/nova/uikit/panel"
          },
          {
            "text": "Flex",
            "link": "/nova/uikit/flex"
          },
          {
            "text": "Grid",
            "link": "/nova/uikit/grid"
          },
          {
            "text": "Stack",
            "link": "/nova/uikit/stack"
          },
          {
            "text": "Spacer",
            "link": "/nova/uikit/spacer"
          }
        ]
      },
      {
        "text": "Текст и display",
        "collapsed": true,
        "items": [
          {
            "text": "TextBlock",
            "link": "/nova/uikit/text-block"
          },
          {
            "text": "Label",
            "link": "/nova/uikit/label"
          },
          {
            "text": "Tag",
            "link": "/nova/uikit/tag"
          },
          {
            "text": "Chip",
            "link": "/nova/uikit/chip"
          },
          {
            "text": "Icon",
            "link": "/nova/uikit/icon"
          },
          {
            "text": "Badge",
            "link": "/nova/uikit/badge"
          },
          {
            "text": "ProgressRing",
            "link": "/nova/uikit/progress-ring"
          },
          {
            "text": "Tooltip content",
            "link": "/nova/uikit/tooltip-content"
          }
        ]
      },
      {
        "text": "Действия и controls",
        "collapsed": true,
        "items": [
          {
            "text": "Button",
            "link": "/nova/uikit/button"
          },
          {
            "text": "ActionList",
            "link": "/nova/uikit/action-list"
          },
          {
            "text": "Toggle",
            "link": "/nova/uikit/toggle"
          },
          {
            "text": "Checkbox",
            "link": "/nova/uikit/checkbox"
          },
          {
            "text": "Slider",
            "link": "/nova/uikit/slider"
          },
          {
            "text": "SegmentedControl",
            "link": "/nova/uikit/segmented-control"
          },
          {
            "text": "Input-like controls",
            "link": "/nova/uikit/input-controls"
          }
        ]
      },
      {
        "text": "Scroll и overlay",
        "collapsed": true,
        "items": [
          {
            "text": "ScrollArea",
            "link": "/nova/uikit/scroll-area"
          },
          {
            "text": "Scrollbar",
            "link": "/nova/uikit/scrollbar"
          },
          {
            "text": "Tooltip",
            "link": "/nova/uikit/tooltip"
          },
          {
            "text": "Popover",
            "link": "/nova/uikit/popover"
          },
          {
            "text": "Overlay registry",
            "link": "/nova/uikit/overlay"
          },
          {
            "text": "Dialog",
            "link": "/nova/uikit/dialog"
          },
          {
            "text": "Toast",
            "link": "/nova/uikit/toast"
          },
          {
            "text": "Overlay layer",
            "link": "/nova/uikit/overlay-layer"
          },
          {
            "text": "Portal strategy",
            "link": "/nova/uikit/portal-strategy"
          }
        ]
      },
      {
        "text": "Resizer primitives",
        "collapsed": true,
        "items": [
          {
            "text": "LazyResizer",
            "link": "/nova/uikit/lazy-resizer"
          },
          {
            "text": "RowResizer",
            "link": "/nova/uikit/row-resizer"
          },
          {
            "text": "ColResizer",
            "link": "/nova/uikit/col-resizer"
          },
          {
            "text": "Split panels",
            "link": "/nova/uikit/split-panels"
          },
          {
            "text": "Resize constraints",
            "link": "/nova/uikit/resize-constraints"
          }
        ]
      },
      {
        "text": "Motion и Sound",
        "collapsed": true,
        "items": [
          {
            "text": "Жизненный цикл motion",
            "link": "/nova/uikit/motion-lifecycle"
          },
          {
            "text": "Tween",
            "link": "/nova/uikit/tween"
          },
          {
            "text": "Timeline",
            "link": "/nova/uikit/timeline"
          },
          {
            "text": "Presets",
            "link": "/nova/uikit/presets"
          },
          {
            "text": "Sound descriptors",
            "link": "/nova/uikit/sound-descriptors"
          },
          {
            "text": "Playback lifecycle",
            "link": "/nova/uikit/playback-lifecycle"
          }
        ]
      },
      {
        "text": "Accessibility",
        "collapsed": true,
        "items": [
          {
            "text": "Focus model",
            "link": "/nova/uikit/focus-model"
          },
          {
            "text": "Keyboard scopes",
            "link": "/nova/uikit/keyboard-scopes"
          },
          {
            "text": "Selection",
            "link": "/nova/uikit/selection"
          },
          {
            "text": "Cursor declarations",
            "link": "/nova/uikit/cursor-declarations"
          },
          {
            "text": "ARIA strategy",
            "link": "/nova/uikit/aria-strategy"
          },
          {
            "text": "Canvas limitations",
            "link": "/nova/uikit/canvas-limitations"
          }
        ]
      },
      {
        "text": "Компоненты данных",
        "collapsed": true,
        "items": [
          {
            "text": "TimelineChart",
            "link": "/nova/uikit/timeline-chart"
          },
          {
            "text": "TimelineChart v2",
            "link": "/nova/uikit/timeline-chart-v2"
          },
          {
            "text": "Data model",
            "link": "/nova/uikit/data-model"
          },
          {
            "text": "Templates",
            "link": "/nova/uikit/templates"
          }
        ]
      },
      {
        "text": "Справочник",
        "collapsed": true,
        "items": [
          {
            "text": "Контракты UI Kit",
            "link": "/nova/uikit/reference-contracts"
          },
          {
            "text": "Props",
            "link": "/nova/uikit/reference-props"
          },
          {
            "text": "Events",
            "link": "/nova/uikit/reference-events"
          },
          {
            "text": "Style properties",
            "link": "/nova/uikit/reference-style-properties"
          },
          {
            "text": "Theme tokens",
            "link": "/nova/uikit/reference-theme-tokens"
          },
          {
            "text": "Package exports",
            "link": "/nova/uikit/reference-exports"
          }
        ]
      }
    ]
  },
  {
    "text": "NovaAdvanced",
    "collapsed": true,
    "items": [
      {
        "text": "Render pipeline",
        "collapsed": false,
        "items": [
          {
            "text": "Scheduler и frame phases",
            "link": "/nova/advanced/scheduler-frame-phases"
          },
          {
            "text": "Compile",
            "link": "/nova/advanced/compile"
          },
          {
            "text": "Replay",
            "link": "/nova/advanced/replay"
          },
          {
            "text": "Ordered schema",
            "link": "/nova/advanced/ordered-schema"
          },
          {
            "text": "Retained runtime",
            "link": "/nova/advanced/retained-runtime"
          }
        ]
      },
      {
        "text": "Оптимизация отрисовки",
        "collapsed": true,
        "items": [
          {
            "text": "Dirty subtree",
            "link": "/nova/advanced/dirty-subtree"
          },
          {
            "text": "Culling",
            "link": "/nova/advanced/culling"
          },
          {
            "text": "Batching",
            "link": "/nova/advanced/batching"
          },
          {
            "text": "Render targets",
            "link": "/nova/advanced/render-targets"
          },
          {
            "text": "DPR и memory limits",
            "link": "/nova/advanced/dpr-memory-limits"
          }
        ]
      },
      {
        "text": "Renderer backend",
        "collapsed": true,
        "items": [
          {
            "text": "Canvas2D backend",
            "link": "/nova/advanced/canvas2d-backend"
          },
          {
            "text": "WebGL2 backend",
            "link": "/nova/advanced/webgl2-backend"
          },
          {
            "text": "Renderer fallback",
            "link": "/nova/advanced/renderer-fallback"
          },
          {
            "text": "Context lifecycle",
            "link": "/nova/advanced/context-lifecycle"
          },
          {
            "text": "Backend diagnostics",
            "link": "/nova/advanced/backend-diagnostics"
          }
        ]
      },
      {
        "text": "Индексы и hit-test",
        "collapsed": true,
        "items": [
          {
            "text": "Spatial index",
            "link": "/nova/advanced/spatial-index"
          },
          {
            "text": "Bounds index",
            "link": "/nova/advanced/bounds-index"
          },
          {
            "text": "Custom hit area",
            "link": "/nova/advanced/custom-hit-area"
          },
          {
            "text": "Dense scenes",
            "link": "/nova/advanced/dense-scenes"
          },
          {
            "text": "Hit-test performance",
            "link": "/nova/advanced/hit-test-performance"
          }
        ]
      },
      {
        "text": "Resources",
        "collapsed": true,
        "items": [
          {
            "text": "Text atlas",
            "link": "/nova/advanced/text-atlas"
          },
          {
            "text": "Texture atlas",
            "link": "/nova/advanced/texture-atlas"
          },
          {
            "text": "Image cache",
            "link": "/nova/advanced/image-cache"
          },
          {
            "text": "Sound cache",
            "link": "/nova/advanced/sound-cache"
          },
          {
            "text": "Assets preload",
            "link": "/nova/advanced/assets-preload"
          }
        ]
      },
      {
        "text": "Runtime context",
        "collapsed": true,
        "items": [
          {
            "text": "Raph data flow",
            "link": "/nova/advanced/raph-data-flow"
          },
          {
            "text": "Provide / inject",
            "link": "/nova/advanced/provide-inject"
          },
          {
            "text": "Scoped cleanup",
            "link": "/nova/advanced/scoped-cleanup"
          },
          {
            "text": "Shared kernel",
            "link": "/nova/advanced/shared-kernel"
          },
          {
            "text": "Timeline invalidation scope",
            "link": "/nova/advanced/timeline-invalidation-scope"
          }
        ]
      },
      {
        "text": "Performance",
        "collapsed": true,
        "items": [
          {
            "text": "Runtime metrics",
            "link": "/nova/advanced/runtime-metrics"
          },
          {
            "text": "Telemetry",
            "link": "/nova/advanced/telemetry"
          },
          {
            "text": "Benchmark methodology",
            "link": "/nova/advanced/benchmark-methodology"
          },
          {
            "text": "Nova vs Pixi",
            "link": "/nova/advanced/nova-vs-pixi"
          },
          {
            "text": "Memory profiling",
            "link": "/nova/advanced/memory-profiling"
          }
        ]
      },
      {
        "text": "DevTools",
        "collapsed": true,
        "items": [
          {
            "text": "Runtime bridge",
            "link": "/nova/advanced/runtime-bridge"
          },
          {
            "text": "Tree inspection",
            "link": "/nova/advanced/tree-inspection"
          },
          {
            "text": "Styles inspection",
            "link": "/nova/advanced/styles-inspection"
          },
          {
            "text": "Renderer diagnostics",
            "link": "/nova/advanced/renderer-diagnostics"
          },
          {
            "text": "Limitations",
            "link": "/nova/advanced/limitations"
          }
        ]
      }
    ]
  },
  {
    "text": "Timeline chart",
    "collapsed": true,
    "items": [
      {
        "text": "Начало",
        "collapsed": false,
        "items": [
          {
            "text": "Быстрый старт",
            "link": "/nova/timeline-chart/quick-start"
          },
          {
            "text": "Опции",
            "link": "/nova/timeline-chart/options"
          },
          {
            "text": "Данные timeline",
            "link": "/nova/timeline-chart/data-model"
          },
          {
            "text": "Группы",
            "link": "/nova/timeline-chart/groups"
          },
          {
            "text": "Задачи",
            "link": "/nova/timeline-chart/tasks"
          },
          {
            "text": "Фоновые задачи",
            "link": "/nova/timeline-chart/background-tasks"
          },
          {
            "text": "Points и links",
            "link": "/nova/timeline-chart/annotations-data-api"
          },
          {
            "text": "Annotations routing",
            "link": "/nova/timeline-chart/annotations-routing-performance"
          },
          {
            "text": "Задачи без группы",
            "link": "/nova/timeline-chart/ungrouped-tasks"
          },
          {
            "text": "Перетаскивание задач",
            "link": "/nova/timeline-chart/task-dragging"
          }
        ]
      },
      {
        "text": "API",
        "collapsed": true,
        "items": [
          {
            "text": "Подключение API",
            "link": "/nova/timeline-chart/api-connect"
          },
          {
            "text": "data",
            "link": "/nova/timeline-chart/api-data-set"
          },
          {
            "text": "options",
            "link": "/nova/timeline-chart/api-options-set"
          },
          {
            "text": "add",
            "link": "/nova/timeline-chart/api-add"
          },
          {
            "text": "update",
            "link": "/nova/timeline-chart/api-update"
          },
          {
            "text": "remove",
            "link": "/nova/timeline-chart/api-remove"
          },
          {
            "text": "batch",
            "link": "/nova/timeline-chart/api-batch"
          },
          {
            "text": "schedule updates",
            "link": "/nova/timeline-chart/api-schedule-updates"
          },
          {
            "text": "flush behavior",
            "link": "/nova/timeline-chart/api-flush-behavior"
          },
          {
            "text": "focusOnTask",
            "link": "/nova/timeline-chart/api-focus-on-task"
          },
          {
            "text": "selectTasks",
            "link": "/nova/timeline-chart/api-select-tasks"
          },
          {
            "text": "refresh",
            "link": "/nova/timeline-chart/api-refresh"
          },
          {
            "text": "Error handling",
            "link": "/nova/timeline-chart/api-error-handling"
          }
        ]
      },
      {
        "text": "Кастомизация",
        "collapsed": true,
        "items": [
          {
            "text": "Task profiles",
            "link": "/nova/timeline-chart/custom-task-profiles"
          },
          {
            "text": "Task template context",
            "link": "/nova/timeline-chart/custom-task-template-context"
          },
          {
            "text": "Task recipes",
            "link": "/nova/timeline-chart/custom-task-recipes"
          },
          {
            "text": "Annotation profiles",
            "link": "/nova/timeline-chart/annotations-profiles"
          },
          {
            "text": "Group column templates",
            "link": "/nova/timeline-chart/custom-group-column-templates"
          },
          {
            "text": "Group header templates",
            "link": "/nova/timeline-chart/custom-group-header-templates"
          },
          {
            "text": "Tooltip templates",
            "link": "/nova/timeline-chart/custom-tooltip-templates"
          },
          {
            "text": "Cluster templates",
            "link": "/nova/timeline-chart/custom-cluster-templates"
          },
          {
            "text": "Shadow templates",
            "link": "/nova/timeline-chart/custom-shadow-templates"
          },
          {
            "text": "CSS-переменные",
            "link": "/nova/timeline-chart/custom-css-variables"
          },
          {
            "text": "NovaCSS @theme",
            "link": "/nova/timeline-chart/custom-novacss-theme"
          },
          {
            "text": "Панели, Grid и TimeScale",
            "link": "/nova/timeline-chart/custom-layout-parts"
          },
          {
            "text": "Grid и шкала времени",
            "link": "/nova/timeline-chart/grid"
          },
          {
            "text": "Themes и styleSheet",
            "link": "/nova/timeline-chart/custom-themes-style-sheet"
          },
          {
            "text": "Assets",
            "link": "/nova/timeline-chart/custom-assets"
          }
        ]
      },
      {
        "text": "Интерактивность",
        "collapsed": true,
        "items": [
          {
            "text": "Pointer events",
            "link": "/nova/timeline-chart/interaction-pointer-events"
          },
          {
            "text": "Selection",
            "link": "/nova/timeline-chart/interaction-selection"
          },
          {
            "text": "Drag lifecycle",
            "link": "/nova/timeline-chart/interaction-drag-lifecycle"
          },
          {
            "text": "Edit modes",
            "link": "/nova/timeline-chart/interaction-edit-modes"
          },
          {
            "text": "Snap при редактировании",
            "link": "/nova/timeline-chart/interaction-snap"
          },
          {
            "text": "Keyboard modifiers",
            "link": "/nova/timeline-chart/interaction-keyboard-modifiers"
          },
          {
            "text": "Range changes",
            "link": "/nova/timeline-chart/interaction-range-changes"
          },
          {
            "text": "Scroll events",
            "link": "/nova/timeline-chart/interaction-scroll-events"
          },
          {
            "text": "Data/options events",
            "link": "/nova/timeline-chart/interaction-data-options-events"
          }
        ]
      },
      {
        "text": "Plugins",
        "collapsed": true,
        "items": [
          {
            "text": "Plugin API",
            "link": "/nova/timeline-chart/plugins-api"
          },
          {
            "text": "Markers",
            "link": "/nova/timeline-chart/plugins-markers"
          },
          {
            "text": "Custom overlays",
            "link": "/nova/timeline-chart/plugins-custom-overlays"
          },
          {
            "text": "Plugin lifecycle",
            "link": "/nova/timeline-chart/plugins-lifecycle"
          },
          {
            "text": "Plugin events",
            "link": "/nova/timeline-chart/plugins-events"
          }
        ]
      },
      {
        "text": "Performance",
        "collapsed": true,
        "items": [
          {
            "text": "Модель производительности",
            "link": "/nova/timeline-chart/performance-model"
          },
          {
            "text": "Batch updates",
            "link": "/nova/timeline-chart/performance-batch-updates"
          },
          {
            "text": "Частые обновления",
            "link": "/nova/timeline-chart/performance-frequent-updates"
          },
          {
            "text": "Большие наборы данных",
            "link": "/nova/timeline-chart/large-data"
          },
          {
            "text": "Rendering optimization",
            "link": "/nova/timeline-chart/performance-rendering-optimization"
          },
          {
            "text": "WASM-оптимизации",
            "link": "/nova/timeline-chart/performance-wasm-optimizations"
          },
          {
            "text": "Text performance",
            "link": "/nova/timeline-chart/performance-text"
          },
          {
            "text": "Data optimization",
            "link": "/nova/timeline-chart/performance-data-optimization"
          },
          {
            "text": "Diagnostics",
            "link": "/nova/timeline-chart/performance-diagnostics"
          },
          {
            "text": "Практические лимиты",
            "link": "/nova/timeline-chart/performance-limits"
          }
        ]
      },
      {
        "text": "API Reference",
        "collapsed": true,
        "items": [
          {
            "text": "Types: TimelineRootData",
            "link": "/nova/timeline-chart/reference-root-data"
          },
          {
            "text": "Types: TimelineGroupInput",
            "link": "/nova/timeline-chart/reference-group-input"
          },
          {
            "text": "Types: TimelineTaskInput",
            "link": "/nova/timeline-chart/reference-task-input"
          },
          {
            "text": "Types: TimelineOptions",
            "link": "/nova/timeline-chart/reference-options"
          },
          {
            "text": "Types: TimelineChartRef",
            "link": "/nova/timeline-chart/reference-chart-ref"
          },
          {
            "text": "Types: Timeline events",
            "link": "/nova/timeline-chart/reference-events"
          },
          {
            "text": "Types: Templates",
            "link": "/nova/timeline-chart/reference-templates"
          },
          {
            "text": "Types: Plugins",
            "link": "/nova/timeline-chart/reference-plugins"
          },
          {
            "text": "Exports",
            "link": "/nova/timeline-chart/reference-exports"
          }
        ]
      },
      {
        "text": "Рецепты",
        "collapsed": true,
        "items": [
          {
            "text": "Одна группа и одна задача",
            "link": "/nova/timeline-chart/recipe-basic"
          },
          {
            "text": "Несколько групп и задач",
            "link": "/nova/timeline-chart/recipe-multiple-groups"
          },
          {
            "text": "Кастомная карточка задачи",
            "link": "/nova/timeline-chart/recipe-task-card"
          },
          {
            "text": "Фоновые интервалы",
            "link": "/nova/timeline-chart/recipe-background-intervals"
          },
          {
            "text": "Readonly timeline",
            "link": "/nova/timeline-chart/recipe-readonly"
          },
          {
            "text": "Кастомные колонки групп",
            "link": "/nova/timeline-chart/recipe-group-columns"
          },
          {
            "text": "Фильтрация групп и задач",
            "link": "/nova/timeline-chart/recipe-filtering"
          },
          {
            "text": "Сортировка групп",
            "link": "/nova/timeline-chart/recipe-group-sorting"
          },
          {
            "text": "Программный focus на задачу",
            "link": "/nova/timeline-chart/recipe-focus-task"
          },
          {
            "text": "Live updates через batch",
            "link": "/nova/timeline-chart/recipe-live-batch"
          },
          {
            "text": "Частые updates с executor",
            "link": "/nova/timeline-chart/recipe-executor-updates"
          },
          {
            "text": "Markers поверх timeline",
            "link": "/nova/timeline-chart/recipe-markers"
          },
          {
            "text": "Annotations cookbook",
            "link": "/nova/timeline-chart/recipe-annotations"
          },
          {
            "text": "Кастомный tooltip",
            "link": "/nova/timeline-chart/recipe-tooltip"
          },
          {
            "text": "Контекстное меню",
            "link": "/nova/timeline-chart/recipe-context-menu"
          }
        ]
      },
      {
        "text": "Дополнительные материалы",
        "collapsed": true,
        "items": [
          {
            "text": "executor",
            "link": "/nova/timeline-chart/options-executor"
          },
          {
            "text": "grid",
            "link": "/nova/timeline-chart/options-grid"
          },
          {
            "text": "groups",
            "link": "/nova/timeline-chart/options-groups"
          },
          {
            "text": "interaction",
            "link": "/nova/timeline-chart/options-interaction"
          },
          {
            "text": "Обзор options",
            "link": "/nova/timeline-chart/options-overview"
          },
          {
            "text": "rendering",
            "link": "/nova/timeline-chart/options-rendering"
          },
          {
            "text": "scroll",
            "link": "/nova/timeline-chart/options-scroll"
          },
          {
            "text": "selection",
            "link": "/nova/timeline-chart/options-selection"
          },
          {
            "text": "snap",
            "link": "/nova/timeline-chart/options-snap"
          },
          {
            "text": "tasks",
            "link": "/nova/timeline-chart/options-tasks"
          },
          {
            "text": "timeRange",
            "link": "/nova/timeline-chart/options-time-range"
          },
          {
            "text": "timeScale",
            "link": "/nova/timeline-chart/options-time-scale"
          },
          {
            "text": "timezone и locale",
            "link": "/nova/timeline-chart/options-timezone-locale"
          },
          {
            "text": "tooltip",
            "link": "/nova/timeline-chart/options-tooltip"
          },
          {
            "text": "ungroupedPanel",
            "link": "/nova/timeline-chart/options-ungrouped-panel"
          },
          {
            "text": "viewport",
            "link": "/nova/timeline-chart/options-viewport"
          },
          {
            "text": "Стабильные id",
            "link": "/nova/timeline-chart/stable-ids"
          }
        ]
      }
    ]
  }
]

export const novaDocumentCount = 256
